name: Deploy from main to prd Databricks

on:
  workflow_dispatch:

jobs:
  deploy-prd:
    name: Checkout main and deploy to prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Git user for push
        run: |
          git config --global user.name "yutakakusumoto"
          git config --global user.email "kusumoto0106@yahoo.co.jp"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to prd environment via asset bundle
        run: databricks bundle deploy
        working-directory: ./bundle
        env:
          DATABRICKS_TOKEN: dapie3cc470d4209cce94bfbbda757f85757
          DATABRICKS_BUNDLE_ENV: prod

      - name: Push same content to stg branch
        run: |
          git checkout -B stg       # stgブランチを作成または切り替え
          git push origin stg --force
